### ISSUE TITLE
Links to files break after moving or renaming files

### ISSUE THREAD

**Issue by TheNomad11** [nextcloud/collectives#1527]
**Describe the bug**
Links to files break after moving or renaming files

**To Reproduce**
1. Make a link from a Collectives page to a pdf file in Files
2. Click on the link
3. The pdf loads correctly
4. Go to Files and move the pdf file
5. Go back to Collectives, reload, and click on the link to the pdf file
6. The pdf file does not load, a message appears "File no loger exists"
7. Copy the link and put in the Browser URL bar
8. The pdf loads

**Expected behavior**
The Pdf link loads, as these links are permanant within Nextcloud.  They still work after moving and renaming

**Server details:**
- Collectives app version: 2.14.14;
- Nextcloud version: [e.g. 30.0.0 (AIO)

**Client details:**
 - OS:  Linux Mint
 - Browser: Firefox
 - Browser version: 131.0.2
 - Device: [Laptop

**Comment by mejo-** [comment]
Hey @TheNomad11, thanks for your report. I'm able to reproduce your bug.

It seems like the server returns an outdated reference object from the cache. We probably need to take care that the the reference cache for files gets invalidated when they get moved or copied.

Cc @juliusknorr as you worked on this in the past.

**Comment by juliusknorr** [comment]
Which URL format is being used? Wondering with the internal URL we should not see any change in the URL with the move and I'd expect that with any other we should still have the file id as identifier, so maybe that is rather a but in the extraction logic to get the file metadata for the specific link

**Comment by mejo-** [comment]
> Which URL format is being used? Wondering with the internal URL we should not see any change in the URL with the move and I'd expect that with any other we should still have the file id as identifier, so maybe that is rather a but in the extraction logic to get the file metadata for the specific link

Exactly, the URL does not change. But the reference response contains the file metadata which contains the file name (which changed) - and apparently this is passed to the viewer for opening the file.

**Comment by Aveyron-RetD** [comment]
I suppose this is linked.
If you copy/paste a collective folder with documents in .attachements in another place (other collective) the documents are not displayed anymore.
Its very confusing because images are displayed correctly and the "actual" link displayed in the error message 
![Image](https://github.com/user-attachments/assets/45f9d1e0-21ff-4da5-bcf2-a60d3a86b4e9)

**Comment by mejo-** [comment]
@TheNomad11 do you still run into this problem? I could imagine it got fixed in the meantime.

>  If you copy/paste a collective folder with documents in .attachements in another place (other collective) the documents are not displayed anymore.

This is a different issue. See #1756

**Comment by mejo-** [comment]
Sorry, I tested now and it's still reproducible.

**Comment by VeroChak** [comment]
Hi there, thanks a lot for addressing this bug.
I am still expieriencing it in Nextcloud 30.0.10 and Collectives App 2.18.0.
What would you suggest?

**Comment by VeroChak** [comment]
The bug still exists. 
I guess I have to use another wiki software :(

**Comment by Aveyron-RetD** [comment]
@VeroChak Have you updated your instance the fix landed in v30.0.12rc1

**Comment by VeroChak** [comment]
@Aveyron-RetD Yes, I use [Nextcloud Hub 26 Winter](https://hetzner.com/) (33.0.6) and the Collectives App 4.5.0.
Here’s how I go about reproducing the bug:
1) Create a new file in the Files app.
2) In the Collectives app, use the link icon in the menu (“Link to file or folder”) to link to the document.
3) Test the link: It works!
4) Rename or move the file in the Files app.
5) Test the link: Error ‘File no longer exists’.
I find this particularly surprising because the internal link to the file remains completely identical: when hovering over the link in the preview in the browser, the exact same internal URL of the document is displayed in all the variants tested.

**Comment by Aveyron-RetD** [comment]
Ok reprocuded thank you @mejo- see above.
clicking on this 

<img width="30" height="30" alt="Image" src="https://github.com/user-attachments/assets/a69d762e-d58c-4bb7-ba7c-7c0571ecbfa3" />

the link open.

clicking on this the link does not open it says the file does not exit.

<img width="342" height="118" alt="Image" src="https://github.com/user-attachments/assets/07f4404d-5e66-44e0-a3a5-ff59337c21de" />

**Comment by Aveyron-RetD** [comment]
By the way  @VeroChak  the "correct way" is to import files into collectives to make sure that people will be able to see the file.

The way you describe you need to make sure to have given access to the file to the team

**Comment by Aveyron-RetD** [comment]
Ok not reproducible in here after a certain amount of time, the link works. I suppose it needs some time to fetch the new URL and the widget gets updated...

**Comment by max-nextcloud** [comment]
@VeroChak 
Do the links also start working for you after some time.

That all sounds different from the original issue here. Could you file it as a new issue so it does not get lost as this one is already closed?
